# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# pre-defined variables: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y build-essential python wget libssl-dev libaio-dev vim git --fix-missing
  displayName: 'update apt and install build tool'

- script: |
    sudo ./pkgdep.sh
  workingDirectory: $(Pipeline.Workspace)/script
  displayName: 'Download required packages'

- script: |
    sudo ./build_lib.sh
  workingDirectory: $(Pipeline.Workspace)/lib
  displayName: 'Download required packages'
